### ISSUE TITLE
Flow ai is writing to disk

### ISSUE THREAD

**Issue by bradfitzgerald** [flow-ai/flowai-js#3]
Unfortunately, flowai writes to disk when running it in nodejs env. That means I cannot use the api in a lambda function, as it does not have access to the file system.

Furthermore, why can't flow ai have a simple endpoint to which we can post? Forcing users to use permanent connection limits the use cases for the tech. Otherwise, it is a great product.

**Comment by Geeza** [comment]
The library uses disk storage to keep track of the threadId (using localStorage in the web variant). I'll create a backlog item that will make this configurable with nodejs

**Comment by Geeza** [comment]
Fixed in 1.6.0
